PopulationRegisterWeb/Models/Categories.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PopulationManagementAPI.Models
{
    public class Categories
    {
        public byte Category_ID { get; set; }
        public string Category_Name { get; set; }
    }
}

PopulationRegisterWeb/Models/ErrorViewModel.cs
using System;

namespace PopulationRegisterWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PopulationRegisterWeb/Models/Genders.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PopulationManagementAPI.Models
{
    public class Genders
    {
        public byte Gender_ID{ get; set; }
        public string Gender_Name { get; set; }

    }
}

PopulationRegisterWeb/Models/PersonsViewModel.cs
using PopulationManagementAPI.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PopulationRegisterWeb.Models
{
    public class PersonsViewModel
    {
        public long Id { get; set; }
        [Required]
        [Display(Name ="First Name")]
        public string FirstName { get; set; }
        [Display(Name ="Midddle Name")]
        public string MiddleName { get; set; }
        [Required]
        [Display(Name ="Last Name")]
        public string LastName { get; set; }
        [Required]
        public DateTime? Dob { get; set; }
        [Required]
        [Display(Name = "Father Name")]

        public string FatherName { get; set; }
        [Required]
        [Display(Name ="Mother Name")]
        public string MotherName { get; set; }
        [Required]
        [Display(Name = "Gender")]

        public byte? GenderId { get; set; }
        [Required]
        [Display(Name = "Category")]

        public byte? CategoryId { get; set; }
        public DateTime AddedOn { get; set; }
        public string AddedByIp { get; set; }
        public int AddedBy { get; set; }
        
    }
}

PopulationRegisterWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PopulationRegisterWeb.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PopulationRegisterWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PopulationRegisterWeb/Controllers/MastersController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PopulationManagementAPI.Models;
using PopulationRegisterWeb.APIDepedency;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace PopulationRegisterWeb.Controllers
{
    public class MastersController : Controller
    {
        public IActionResult Genders()
        {
            IEnumerable<Genders> lstGenders = new List<Genders>();
            ConnectionToAPI objConnectionToAPI = new ConnectionToAPI("masters/Genders", "GET");
            objConnectionToAPI.IsHttpsEnable = true;
            objConnectionToAPI.ContentType = "application/json";
            objConnectionToAPI.KeepAlive = false;
            lstGenders = objConnectionToAPI.DownloadAs<List<Genders>>();
            return Json(lstGenders);
        }
        public IActionResult Categories()
        {
            IEnumerable<Categories> lstCategories = new List<Categories>();

            ConnectionToAPI objConnectionToAPI = new ConnectionToAPI("masters/Categories", "GET");
            objConnectionToAPI.IsHttpsEnable = true;
            objConnectionToAPI.ContentType = "application/json";
            objConnectionToAPI.KeepAlive = false;
            lstCategories = objConnectionToAPI.DownloadAs<List<Categories>>();
            return Json(lstCategories);
        }
    }
}

PopulationRegisterWeb/Controllers/PopulationRegisterController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PopulationRegisterWeb.APIDepedency;
using PopulationRegisterWeb.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;

namespace PopulationRegisterWeb.Controllers
{
    public class PopulationRegisterController : Controller
    {
        // GET: PopulationRegisterController
        public ActionResult Index()
        {
            IEnumerable<PersonsViewModel> lstPersons = new List<PersonsViewModel>();

            ConnectionToAPI objConnectionToAPI = new ConnectionToAPI("Persons", "GET");
            objConnectionToAPI.IsHttpsEnable = true;
            objConnectionToAPI.ContentType = "application/json";
            objConnectionToAPI.KeepAlive = false;
            lstPersons = objConnectionToAPI.DownloadAs<List<PersonsViewModel>>();

            return View(lstPersons);
        }

        // GET: PopulationRegisterController/Create
        public ActionResult Create()
        {
            PersonsViewModel personsViewModel = new PersonsViewModel();
            return View(personsViewModel);
        }

        // POST: PopulationRegisterController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(PersonsViewModel obj)
        {

            obj.AddedBy = 1;
            obj.AddedByIp =ControllerContext.HttpContext.Connection.RemoteIpAddress.ToString();
            obj.AddedOn = DateTime.Now;

            ConnectionToAPI objConnectionToAPI = new ConnectionToAPI("Persons/Save", "POST");
            objConnectionToAPI.IsHttpsEnable = true;
            objConnectionToAPI.ContentType = "application/json";
            objConnectionToAPI.KeepAlive = false;

            await objConnectionToAPI.PassDataToSendAsync(obj);

            KeyValuePair<string, string> response = await objConnectionToAPI.UploadDataAndGetResponseAsync();

            if (response.Key == "OK")
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(obj);
            }
        }
    }
}

PopulationRegisterWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PopulationRegisterWeb/Views/PopulationRegister/Create.cshtml
@model PopulationRegisterWeb.Models.PersonsViewModel

@{
    ViewData["Title"] = "Create";
}
<div class="card">
    <div class="card-header alert-danger">Add Person Register in Census Survey 2023</div>
    <div class="card-body">
        <form asp-action="Create">
            <div class="row">

                <div class="col-md-4">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="FirstName" class="control-label"></label>
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="MiddleName" class="control-label"></label>
                        <input asp-for="MiddleName" class="form-control" />
                        <span asp-validation-for="MiddleName" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="LastName" class="control-label"></label>
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="Dob" class="control-label"></label>
                        <input asp-for="Dob" class="form-control" />
                        <span asp-validation-for="Dob" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="FatherName" class="control-label"></label>
                        <input asp-for="FatherName" class="form-control" />
                        <span asp-validation-for="FatherName" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="MotherName" class="control-label"></label>
                        <input asp-for="MotherName" class="form-control" />
                        <span asp-validation-for="MotherName" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="GenderId" class="control-label"></label>
                        <select asp-for="GenderId" class="form-control" id="ddlGenders">
                        </select>
                        <span asp-validation-for="GenderId" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="CategoryId" class="control-label"></label>
                        <select asp-for="CategoryId" class="form-control" id="ddlCategories"></select>
                        <span asp-validation-for="CategoryId" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <hr />
            <div class="row">
                <div class="col-md-12">
                    <div class="form-check-inline">
                        <input type="submit" value="Register" class="btn btn-primary" />
                        &nbsp;&nbsp;  <a asp-action="Index" class="btn btn-info">View All</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script type="text/javascript">
        var ddlGenders;
        var ddlCategories;
        var oData;
        $(document).ready(function () {
            ddlGenders = $("#ddlGenders");
            ddlCategories = $("#ddlCategories");
            fnGenders(ddlGenders);
            fnCategories(ddlCategories);
        });
        function fnGenders(control) {
            $.ajax({
                url: "/Masters/Genders",
                type: "GET",
                dataType: "",
                contentType: "application/json",
                success: function (oServerData) {
                    oData = oServerData;
                    ddlGenders.empty();
                    ddlGenders.append('<option value="">Select Gender</option>');
                    $(oServerData).each(function (index, item) {
                        ddlGenders.append('<option value=' + item.gender_ID + '>' + item.gender_Name + '</option>');
                    });
                },
                error: function (xhr, status, err) {

                }
            });
        }
        function fnCategories(control) {
            $.ajax({
                url: "/Masters/Categories",
                type: "GET",
                dataType: "",
                contentType: "application/json",
                success: function (oServerData) {
                    oData = oServerData;
                    ddlCategories.empty();
                    ddlCategories.append('<option  value="">Select Category</option>');
                    $(oServerData).each(function (index, item) {
                        ddlCategories.append('<option value=' + item.category_ID + '>' + item.category_Name + '</option>');
                    });
                },
                error: function (xhr, status, err) {

                }
            });
        }
    </script>
}

PopulationRegisterWeb/Views/PopulationRegister/Index.cshtml
@model IEnumerable<PersonsViewModel>
<div class="card">
    <div class="card-header alert-success">View Person List Registered in Census Survey 2023</div>
    <div class="card-body">
        <div class="col-md-12">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>S.No.</th>
                        <th>First Name</th>
                        <th>Middle Name</th>
                        <th>Last Name</th>
                        <th>DOB</th>
                        <th>Category</th>
                        <th>Gender</th>
                        <th>Father Name</th>
                        <th>Mother Name</th>
                        <th>Added By</th>
                        <th>Added By IP</th>
                        <th>Added On</th>
                    </tr>
                </thead> @{int Sno = 0; }
                @foreach (var objPerson in Model)
                {

                    <tr>
                        <td>@(++Sno)</td>
                        <td>@objPerson.FirstName</td>
                        <td>@objPerson.MiddleName</td>
                        <td>@objPerson.LastName</td>
                        <td>@objPerson.Dob</td>
                        <td>@objPerson.CategoryId</td>
                        <td>@objPerson.GenderId</td>
                        <td>@objPerson.FatherName</td>
                        <td>@objPerson.MotherName</td>
                        <td>@objPerson.AddedBy</td>
                        <td>@objPerson.AddedByIp</td>
                        <td>@objPerson.AddedOn</td>
                    </tr>
                }
            </table>
        </div>
    </div>
    <div class="card-footer alert-success">
        <a asp-action="Create" asp-controller="PopulationRegister" class="btn btn-success">Register More Person</a>
    </div>
</div>

PopulationRegisterWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Census Survey 2023 [2021]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PopulationRegisterWeb</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PopulationRegister" asp-action="Index">Registrations</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PopulationRegisterWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>